### PR TITLE
More data cleaning

### PR DESCRIPTION
**Pull request by sjgraupman**
looked into fake counties on liquor data. Code may need to be cleaned up

### CODE REVIEW

**Comment by fruzyna** [comment]
We should switch to .py files so we can actually to merging...

I was going to manually merge but Jupyter failed to open your notebook.

**Comment by sjgraupman** [comment]
I agree. I was trying to go through and manually merge the conflicts but there was too much metadata for me to figure out where the actual code was. I'll work on converting mine to a .py file. Should be pretty easy

**Comment by fruzyna** [comment]
I found a solution that automatically saves your notebook as a .py file automatically [here](https://stackoverflow.com/a/25765194/1168052)

My next commit will include the .py file version

**Comment by fruzyna** [comment]
Commit is up. I added notebooks to the .gitignore so they can't be uploaded anymore, but I added a script to convert the automatically generated .py back to a .ipynb for ease of editing.

I'm going to close this pull request because its a lost cause at this point. Feel free to try again with the new script.

Let me know if there are any questions,

**Pull request closed without merging**
